/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMTaxRouteImport } from './routes/_authenticated/m/tax'
import { Route as AuthenticatedMSalesRouteImport } from './routes/_authenticated/m/sales'
import { Route as AuthenticatedMReportsRouteImport } from './routes/_authenticated/m/reports'
import { Route as AuthenticatedMInventoryRouteImport } from './routes/_authenticated/m/inventory'
import { Route as AuthenticatedMFinanceRouteImport } from './routes/_authenticated/m/finance'
import { Route as AuthenticatedMEmployeesRouteImport } from './routes/_authenticated/m/employees'
import { Route as AuthenticatedMCrmRouteImport } from './routes/_authenticated/m/crm'
import { Route as AuthenticatedMAdminRouteImport } from './routes/_authenticated/m/admin'
import { Route as AuthenticatedMCrmIndexRouteImport } from './routes/_authenticated/m/crm.index'
import { Route as AuthenticatedMTaxWithholdingRouteImport } from './routes/_authenticated/m/tax.withholding'
import { Route as AuthenticatedMTaxVatRouteImport } from './routes/_authenticated/m/tax.vat'
import { Route as AuthenticatedMTaxSalesRouteImport } from './routes/_authenticated/m/tax.sales'
import { Route as AuthenticatedMTaxReportsRouteImport } from './routes/_authenticated/m/tax.reports'
import { Route as AuthenticatedMTaxPurchasesRouteImport } from './routes/_authenticated/m/tax.purchases'
import { Route as AuthenticatedMTaxIncomeRouteImport } from './routes/_authenticated/m/tax.income'
import { Route as AuthenticatedMTaxImportRouteImport } from './routes/_authenticated/m/tax.import'
import { Route as AuthenticatedMTaxExpensesRouteImport } from './routes/_authenticated/m/tax.expenses'
import { Route as AuthenticatedMTaxDocumentsRouteImport } from './routes/_authenticated/m/tax.documents'
import { Route as AuthenticatedMTaxCalendarRouteImport } from './routes/_authenticated/m/tax.calendar'
import { Route as AuthenticatedMTaxAssetsRouteImport } from './routes/_authenticated/m/tax.assets'
import { Route as AuthenticatedMCrmReportsRouteImport } from './routes/_authenticated/m/crm.reports'
import { Route as AuthenticatedMCrmCustomersRouteImport } from './routes/_authenticated/m/crm.customers'
import { Route as AuthenticatedMCrmChannelsRouteImport } from './routes/_authenticated/m/crm.channels'
import { Route as AuthenticatedMCrmCampaignsRouteImport } from './routes/_authenticated/m/crm.campaigns'
import { Route as AuthenticatedMCrmAnalyticsRouteImport } from './routes/_authenticated/m/crm.analytics'
import { Route as AuthenticatedMCrmCustomersIdRouteImport } from './routes/_authenticated/m/crm.customers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMTaxRoute = AuthenticatedMTaxRouteImport.update({
  id: '/m/tax',
  path: '/m/tax',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMSalesRoute = AuthenticatedMSalesRouteImport.update({
  id: '/m/sales',
  path: '/m/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMReportsRoute = AuthenticatedMReportsRouteImport.update({
  id: '/m/reports',
  path: '/m/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMInventoryRoute = AuthenticatedMInventoryRouteImport.update({
  id: '/m/inventory',
  path: '/m/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMFinanceRoute = AuthenticatedMFinanceRouteImport.update({
  id: '/m/finance',
  path: '/m/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMEmployeesRoute = AuthenticatedMEmployeesRouteImport.update({
  id: '/m/employees',
  path: '/m/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMCrmRoute = AuthenticatedMCrmRouteImport.update({
  id: '/m/crm',
  path: '/m/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMAdminRoute = AuthenticatedMAdminRouteImport.update({
  id: '/m/admin',
  path: '/m/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMCrmIndexRoute = AuthenticatedMCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMCrmRoute,
} as any)
const AuthenticatedMTaxWithholdingRoute =
  AuthenticatedMTaxWithholdingRouteImport.update({
    id: '/withholding',
    path: '/withholding',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxVatRoute = AuthenticatedMTaxVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxSalesRoute = AuthenticatedMTaxSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxReportsRoute =
  AuthenticatedMTaxReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxPurchasesRoute =
  AuthenticatedMTaxPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxIncomeRoute = AuthenticatedMTaxIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxImportRoute = AuthenticatedMTaxImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxExpensesRoute =
  AuthenticatedMTaxExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxDocumentsRoute =
  AuthenticatedMTaxDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxCalendarRoute =
  AuthenticatedMTaxCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxAssetsRoute = AuthenticatedMTaxAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMCrmReportsRoute =
  AuthenticatedMCrmReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmCustomersRoute =
  AuthenticatedMCrmCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmChannelsRoute =
  AuthenticatedMCrmChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmCampaignsRoute =
  AuthenticatedMCrmCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmAnalyticsRoute =
  AuthenticatedMCrmAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmCustomersIdRoute =
  AuthenticatedMCrmCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMCrmCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pos': typeof AuthenticatedPosRoute
  '/m/admin': typeof AuthenticatedMAdminRoute
  '/m/crm': typeof AuthenticatedMCrmRouteWithChildren
  '/m/employees': typeof AuthenticatedMEmployeesRoute
  '/m/finance': typeof AuthenticatedMFinanceRoute
  '/m/inventory': typeof AuthenticatedMInventoryRoute
  '/m/reports': typeof AuthenticatedMReportsRoute
  '/m/sales': typeof AuthenticatedMSalesRoute
  '/m/tax': typeof AuthenticatedMTaxRouteWithChildren
  '/m/crm/analytics': typeof AuthenticatedMCrmAnalyticsRoute
  '/m/crm/campaigns': typeof AuthenticatedMCrmCampaignsRoute
  '/m/crm/channels': typeof AuthenticatedMCrmChannelsRoute
  '/m/crm/customers': typeof AuthenticatedMCrmCustomersRouteWithChildren
  '/m/crm/reports': typeof AuthenticatedMCrmReportsRoute
  '/m/tax/assets': typeof AuthenticatedMTaxAssetsRoute
  '/m/tax/calendar': typeof AuthenticatedMTaxCalendarRoute
  '/m/tax/documents': typeof AuthenticatedMTaxDocumentsRoute
  '/m/tax/expenses': typeof AuthenticatedMTaxExpensesRoute
  '/m/tax/import': typeof AuthenticatedMTaxImportRoute
  '/m/tax/income': typeof AuthenticatedMTaxIncomeRoute
  '/m/tax/purchases': typeof AuthenticatedMTaxPurchasesRoute
  '/m/tax/reports': typeof AuthenticatedMTaxReportsRoute
  '/m/tax/sales': typeof AuthenticatedMTaxSalesRoute
  '/m/tax/vat': typeof AuthenticatedMTaxVatRoute
  '/m/tax/withholding': typeof AuthenticatedMTaxWithholdingRoute
  '/m/crm/': typeof AuthenticatedMCrmIndexRoute
  '/m/crm/customers/$id': typeof AuthenticatedMCrmCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pos': typeof AuthenticatedPosRoute
  '/m/admin': typeof AuthenticatedMAdminRoute
  '/m/employees': typeof AuthenticatedMEmployeesRoute
  '/m/finance': typeof AuthenticatedMFinanceRoute
  '/m/inventory': typeof AuthenticatedMInventoryRoute
  '/m/reports': typeof AuthenticatedMReportsRoute
  '/m/sales': typeof AuthenticatedMSalesRoute
  '/m/tax': typeof AuthenticatedMTaxRouteWithChildren
  '/m/crm/analytics': typeof AuthenticatedMCrmAnalyticsRoute
  '/m/crm/campaigns': typeof AuthenticatedMCrmCampaignsRoute
  '/m/crm/channels': typeof AuthenticatedMCrmChannelsRoute
  '/m/crm/customers': typeof AuthenticatedMCrmCustomersRouteWithChildren
  '/m/crm/reports': typeof AuthenticatedMCrmReportsRoute
  '/m/tax/assets': typeof AuthenticatedMTaxAssetsRoute
  '/m/tax/calendar': typeof AuthenticatedMTaxCalendarRoute
  '/m/tax/documents': typeof AuthenticatedMTaxDocumentsRoute
  '/m/tax/expenses': typeof AuthenticatedMTaxExpensesRoute
  '/m/tax/import': typeof AuthenticatedMTaxImportRoute
  '/m/tax/income': typeof AuthenticatedMTaxIncomeRoute
  '/m/tax/purchases': typeof AuthenticatedMTaxPurchasesRoute
  '/m/tax/reports': typeof AuthenticatedMTaxReportsRoute
  '/m/tax/sales': typeof AuthenticatedMTaxSalesRoute
  '/m/tax/vat': typeof AuthenticatedMTaxVatRoute
  '/m/tax/withholding': typeof AuthenticatedMTaxWithholdingRoute
  '/m/crm': typeof AuthenticatedMCrmIndexRoute
  '/m/crm/customers/$id': typeof AuthenticatedMCrmCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/m/admin': typeof AuthenticatedMAdminRoute
  '/_authenticated/m/crm': typeof AuthenticatedMCrmRouteWithChildren
  '/_authenticated/m/employees': typeof AuthenticatedMEmployeesRoute
  '/_authenticated/m/finance': typeof AuthenticatedMFinanceRoute
  '/_authenticated/m/inventory': typeof AuthenticatedMInventoryRoute
  '/_authenticated/m/reports': typeof AuthenticatedMReportsRoute
  '/_authenticated/m/sales': typeof AuthenticatedMSalesRoute
  '/_authenticated/m/tax': typeof AuthenticatedMTaxRouteWithChildren
  '/_authenticated/m/crm/analytics': typeof AuthenticatedMCrmAnalyticsRoute
  '/_authenticated/m/crm/campaigns': typeof AuthenticatedMCrmCampaignsRoute
  '/_authenticated/m/crm/channels': typeof AuthenticatedMCrmChannelsRoute
  '/_authenticated/m/crm/customers': typeof AuthenticatedMCrmCustomersRouteWithChildren
  '/_authenticated/m/crm/reports': typeof AuthenticatedMCrmReportsRoute
  '/_authenticated/m/tax/assets': typeof AuthenticatedMTaxAssetsRoute
  '/_authenticated/m/tax/calendar': typeof AuthenticatedMTaxCalendarRoute
  '/_authenticated/m/tax/documents': typeof AuthenticatedMTaxDocumentsRoute
  '/_authenticated/m/tax/expenses': typeof AuthenticatedMTaxExpensesRoute
  '/_authenticated/m/tax/import': typeof AuthenticatedMTaxImportRoute
  '/_authenticated/m/tax/income': typeof AuthenticatedMTaxIncomeRoute
  '/_authenticated/m/tax/purchases': typeof AuthenticatedMTaxPurchasesRoute
  '/_authenticated/m/tax/reports': typeof AuthenticatedMTaxReportsRoute
  '/_authenticated/m/tax/sales': typeof AuthenticatedMTaxSalesRoute
  '/_authenticated/m/tax/vat': typeof AuthenticatedMTaxVatRoute
  '/_authenticated/m/tax/withholding': typeof AuthenticatedMTaxWithholdingRoute
  '/_authenticated/m/crm/': typeof AuthenticatedMCrmIndexRoute
  '/_authenticated/m/crm/customers/$id': typeof AuthenticatedMCrmCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pos'
    | '/m/admin'
    | '/m/crm'
    | '/m/employees'
    | '/m/finance'
    | '/m/inventory'
    | '/m/reports'
    | '/m/sales'
    | '/m/tax'
    | '/m/crm/analytics'
    | '/m/crm/campaigns'
    | '/m/crm/channels'
    | '/m/crm/customers'
    | '/m/crm/reports'
    | '/m/tax/assets'
    | '/m/tax/calendar'
    | '/m/tax/documents'
    | '/m/tax/expenses'
    | '/m/tax/import'
    | '/m/tax/income'
    | '/m/tax/purchases'
    | '/m/tax/reports'
    | '/m/tax/sales'
    | '/m/tax/vat'
    | '/m/tax/withholding'
    | '/m/crm/'
    | '/m/crm/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pos'
    | '/m/admin'
    | '/m/employees'
    | '/m/finance'
    | '/m/inventory'
    | '/m/reports'
    | '/m/sales'
    | '/m/tax'
    | '/m/crm/analytics'
    | '/m/crm/campaigns'
    | '/m/crm/channels'
    | '/m/crm/customers'
    | '/m/crm/reports'
    | '/m/tax/assets'
    | '/m/tax/calendar'
    | '/m/tax/documents'
    | '/m/tax/expenses'
    | '/m/tax/import'
    | '/m/tax/income'
    | '/m/tax/purchases'
    | '/m/tax/reports'
    | '/m/tax/sales'
    | '/m/tax/vat'
    | '/m/tax/withholding'
    | '/m/crm'
    | '/m/crm/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/pos'
    | '/_authenticated/m/admin'
    | '/_authenticated/m/crm'
    | '/_authenticated/m/employees'
    | '/_authenticated/m/finance'
    | '/_authenticated/m/inventory'
    | '/_authenticated/m/reports'
    | '/_authenticated/m/sales'
    | '/_authenticated/m/tax'
    | '/_authenticated/m/crm/analytics'
    | '/_authenticated/m/crm/campaigns'
    | '/_authenticated/m/crm/channels'
    | '/_authenticated/m/crm/customers'
    | '/_authenticated/m/crm/reports'
    | '/_authenticated/m/tax/assets'
    | '/_authenticated/m/tax/calendar'
    | '/_authenticated/m/tax/documents'
    | '/_authenticated/m/tax/expenses'
    | '/_authenticated/m/tax/import'
    | '/_authenticated/m/tax/income'
    | '/_authenticated/m/tax/purchases'
    | '/_authenticated/m/tax/reports'
    | '/_authenticated/m/tax/sales'
    | '/_authenticated/m/tax/vat'
    | '/_authenticated/m/tax/withholding'
    | '/_authenticated/m/crm/'
    | '/_authenticated/m/crm/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/tax': {
      id: '/_authenticated/m/tax'
      path: '/m/tax'
      fullPath: '/m/tax'
      preLoaderRoute: typeof AuthenticatedMTaxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/sales': {
      id: '/_authenticated/m/sales'
      path: '/m/sales'
      fullPath: '/m/sales'
      preLoaderRoute: typeof AuthenticatedMSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/reports': {
      id: '/_authenticated/m/reports'
      path: '/m/reports'
      fullPath: '/m/reports'
      preLoaderRoute: typeof AuthenticatedMReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/inventory': {
      id: '/_authenticated/m/inventory'
      path: '/m/inventory'
      fullPath: '/m/inventory'
      preLoaderRoute: typeof AuthenticatedMInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/finance': {
      id: '/_authenticated/m/finance'
      path: '/m/finance'
      fullPath: '/m/finance'
      preLoaderRoute: typeof AuthenticatedMFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/employees': {
      id: '/_authenticated/m/employees'
      path: '/m/employees'
      fullPath: '/m/employees'
      preLoaderRoute: typeof AuthenticatedMEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/crm': {
      id: '/_authenticated/m/crm'
      path: '/m/crm'
      fullPath: '/m/crm'
      preLoaderRoute: typeof AuthenticatedMCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/admin': {
      id: '/_authenticated/m/admin'
      path: '/m/admin'
      fullPath: '/m/admin'
      preLoaderRoute: typeof AuthenticatedMAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/crm/': {
      id: '/_authenticated/m/crm/'
      path: '/'
      fullPath: '/m/crm/'
      preLoaderRoute: typeof AuthenticatedMCrmIndexRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/tax/withholding': {
      id: '/_authenticated/m/tax/withholding'
      path: '/withholding'
      fullPath: '/m/tax/withholding'
      preLoaderRoute: typeof AuthenticatedMTaxWithholdingRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/vat': {
      id: '/_authenticated/m/tax/vat'
      path: '/vat'
      fullPath: '/m/tax/vat'
      preLoaderRoute: typeof AuthenticatedMTaxVatRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/sales': {
      id: '/_authenticated/m/tax/sales'
      path: '/sales'
      fullPath: '/m/tax/sales'
      preLoaderRoute: typeof AuthenticatedMTaxSalesRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/reports': {
      id: '/_authenticated/m/tax/reports'
      path: '/reports'
      fullPath: '/m/tax/reports'
      preLoaderRoute: typeof AuthenticatedMTaxReportsRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/purchases': {
      id: '/_authenticated/m/tax/purchases'
      path: '/purchases'
      fullPath: '/m/tax/purchases'
      preLoaderRoute: typeof AuthenticatedMTaxPurchasesRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/income': {
      id: '/_authenticated/m/tax/income'
      path: '/income'
      fullPath: '/m/tax/income'
      preLoaderRoute: typeof AuthenticatedMTaxIncomeRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/import': {
      id: '/_authenticated/m/tax/import'
      path: '/import'
      fullPath: '/m/tax/import'
      preLoaderRoute: typeof AuthenticatedMTaxImportRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/expenses': {
      id: '/_authenticated/m/tax/expenses'
      path: '/expenses'
      fullPath: '/m/tax/expenses'
      preLoaderRoute: typeof AuthenticatedMTaxExpensesRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/documents': {
      id: '/_authenticated/m/tax/documents'
      path: '/documents'
      fullPath: '/m/tax/documents'
      preLoaderRoute: typeof AuthenticatedMTaxDocumentsRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/calendar': {
      id: '/_authenticated/m/tax/calendar'
      path: '/calendar'
      fullPath: '/m/tax/calendar'
      preLoaderRoute: typeof AuthenticatedMTaxCalendarRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/assets': {
      id: '/_authenticated/m/tax/assets'
      path: '/assets'
      fullPath: '/m/tax/assets'
      preLoaderRoute: typeof AuthenticatedMTaxAssetsRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/crm/reports': {
      id: '/_authenticated/m/crm/reports'
      path: '/reports'
      fullPath: '/m/crm/reports'
      preLoaderRoute: typeof AuthenticatedMCrmReportsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/customers': {
      id: '/_authenticated/m/crm/customers'
      path: '/customers'
      fullPath: '/m/crm/customers'
      preLoaderRoute: typeof AuthenticatedMCrmCustomersRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/channels': {
      id: '/_authenticated/m/crm/channels'
      path: '/channels'
      fullPath: '/m/crm/channels'
      preLoaderRoute: typeof AuthenticatedMCrmChannelsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/campaigns': {
      id: '/_authenticated/m/crm/campaigns'
      path: '/campaigns'
      fullPath: '/m/crm/campaigns'
      preLoaderRoute: typeof AuthenticatedMCrmCampaignsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/analytics': {
      id: '/_authenticated/m/crm/analytics'
      path: '/analytics'
      fullPath: '/m/crm/analytics'
      preLoaderRoute: typeof AuthenticatedMCrmAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/customers/$id': {
      id: '/_authenticated/m/crm/customers/$id'
      path: '/$id'
      fullPath: '/m/crm/customers/$id'
      preLoaderRoute: typeof AuthenticatedMCrmCustomersIdRouteImport
      parentRoute: typeof AuthenticatedMCrmCustomersRoute
    }
  }
}

interface AuthenticatedMCrmCustomersRouteChildren {
  AuthenticatedMCrmCustomersIdRoute: typeof AuthenticatedMCrmCustomersIdRoute
}

const AuthenticatedMCrmCustomersRouteChildren: AuthenticatedMCrmCustomersRouteChildren =
  {
    AuthenticatedMCrmCustomersIdRoute: AuthenticatedMCrmCustomersIdRoute,
  }

const AuthenticatedMCrmCustomersRouteWithChildren =
  AuthenticatedMCrmCustomersRoute._addFileChildren(
    AuthenticatedMCrmCustomersRouteChildren,
  )

interface AuthenticatedMCrmRouteChildren {
  AuthenticatedMCrmAnalyticsRoute: typeof AuthenticatedMCrmAnalyticsRoute
  AuthenticatedMCrmCampaignsRoute: typeof AuthenticatedMCrmCampaignsRoute
  AuthenticatedMCrmChannelsRoute: typeof AuthenticatedMCrmChannelsRoute
  AuthenticatedMCrmCustomersRoute: typeof AuthenticatedMCrmCustomersRouteWithChildren
  AuthenticatedMCrmReportsRoute: typeof AuthenticatedMCrmReportsRoute
  AuthenticatedMCrmIndexRoute: typeof AuthenticatedMCrmIndexRoute
}

const AuthenticatedMCrmRouteChildren: AuthenticatedMCrmRouteChildren = {
  AuthenticatedMCrmAnalyticsRoute: AuthenticatedMCrmAnalyticsRoute,
  AuthenticatedMCrmCampaignsRoute: AuthenticatedMCrmCampaignsRoute,
  AuthenticatedMCrmChannelsRoute: AuthenticatedMCrmChannelsRoute,
  AuthenticatedMCrmCustomersRoute: AuthenticatedMCrmCustomersRouteWithChildren,
  AuthenticatedMCrmReportsRoute: AuthenticatedMCrmReportsRoute,
  AuthenticatedMCrmIndexRoute: AuthenticatedMCrmIndexRoute,
}

const AuthenticatedMCrmRouteWithChildren =
  AuthenticatedMCrmRoute._addFileChildren(AuthenticatedMCrmRouteChildren)

interface AuthenticatedMTaxRouteChildren {
  AuthenticatedMTaxAssetsRoute: typeof AuthenticatedMTaxAssetsRoute
  AuthenticatedMTaxCalendarRoute: typeof AuthenticatedMTaxCalendarRoute
  AuthenticatedMTaxDocumentsRoute: typeof AuthenticatedMTaxDocumentsRoute
  AuthenticatedMTaxExpensesRoute: typeof AuthenticatedMTaxExpensesRoute
  AuthenticatedMTaxImportRoute: typeof AuthenticatedMTaxImportRoute
  AuthenticatedMTaxIncomeRoute: typeof AuthenticatedMTaxIncomeRoute
  AuthenticatedMTaxPurchasesRoute: typeof AuthenticatedMTaxPurchasesRoute
  AuthenticatedMTaxReportsRoute: typeof AuthenticatedMTaxReportsRoute
  AuthenticatedMTaxSalesRoute: typeof AuthenticatedMTaxSalesRoute
  AuthenticatedMTaxVatRoute: typeof AuthenticatedMTaxVatRoute
  AuthenticatedMTaxWithholdingRoute: typeof AuthenticatedMTaxWithholdingRoute
}

const AuthenticatedMTaxRouteChildren: AuthenticatedMTaxRouteChildren = {
  AuthenticatedMTaxAssetsRoute: AuthenticatedMTaxAssetsRoute,
  AuthenticatedMTaxCalendarRoute: AuthenticatedMTaxCalendarRoute,
  AuthenticatedMTaxDocumentsRoute: AuthenticatedMTaxDocumentsRoute,
  AuthenticatedMTaxExpensesRoute: AuthenticatedMTaxExpensesRoute,
  AuthenticatedMTaxImportRoute: AuthenticatedMTaxImportRoute,
  AuthenticatedMTaxIncomeRoute: AuthenticatedMTaxIncomeRoute,
  AuthenticatedMTaxPurchasesRoute: AuthenticatedMTaxPurchasesRoute,
  AuthenticatedMTaxReportsRoute: AuthenticatedMTaxReportsRoute,
  AuthenticatedMTaxSalesRoute: AuthenticatedMTaxSalesRoute,
  AuthenticatedMTaxVatRoute: AuthenticatedMTaxVatRoute,
  AuthenticatedMTaxWithholdingRoute: AuthenticatedMTaxWithholdingRoute,
}

const AuthenticatedMTaxRouteWithChildren =
  AuthenticatedMTaxRoute._addFileChildren(AuthenticatedMTaxRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedMAdminRoute: typeof AuthenticatedMAdminRoute
  AuthenticatedMCrmRoute: typeof AuthenticatedMCrmRouteWithChildren
  AuthenticatedMEmployeesRoute: typeof AuthenticatedMEmployeesRoute
  AuthenticatedMFinanceRoute: typeof AuthenticatedMFinanceRoute
  AuthenticatedMInventoryRoute: typeof AuthenticatedMInventoryRoute
  AuthenticatedMReportsRoute: typeof AuthenticatedMReportsRoute
  AuthenticatedMSalesRoute: typeof AuthenticatedMSalesRoute
  AuthenticatedMTaxRoute: typeof AuthenticatedMTaxRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedMAdminRoute: AuthenticatedMAdminRoute,
  AuthenticatedMCrmRoute: AuthenticatedMCrmRouteWithChildren,
  AuthenticatedMEmployeesRoute: AuthenticatedMEmployeesRoute,
  AuthenticatedMFinanceRoute: AuthenticatedMFinanceRoute,
  AuthenticatedMInventoryRoute: AuthenticatedMInventoryRoute,
  AuthenticatedMReportsRoute: AuthenticatedMReportsRoute,
  AuthenticatedMSalesRoute: AuthenticatedMSalesRoute,
  AuthenticatedMTaxRoute: AuthenticatedMTaxRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
